### PR TITLE
Add RMT LED support

### PR DESCRIPTION
**Pull request by jetpax**
This PR adds support for an addressable LED eg as fitted to the ESP Devkit-M

It displays diag codes , eg blink twice during wifi connect, blink once when connected

It uses the  espressif/led_strip: "^2.5.2" managed component

The color/brightness can be changed by issuing a command like 

`{"type":"request","target":"rmtled","name":"color","data": [0,128,0]}`

to set the LED to green with half brightness

To enable it,  pass the desired pin to the constructor in main eg

`  dev::useRmtled(GPIO_NUM_48);`

### CODE REVIEW

**Comment by dyarkovoy** [comment]
Thank you, @jetpax,
do we really need `espressif__led_strip` in CMakeLists.txt? I believe adding dependency to esp32m/idf_component.yml is sufficient, can you check?

**Comment by jetpax** [comment]
Wouldnt compile for me without it, but maybe there is another way I am not aware of?

**Comment by dyarkovoy** [comment]
Okay, I tried to compile it on my end and I see the problem. The component needs a "public: true" declaration in idf_component.yml:
```
  espressif/led_strip:
    public: true
    version: "^2.5.2"
```

Please try to compile with this change and with `espressif__led_strip` removed from CMakeLists.txt, it seems to be working for me

**Comment by jetpax** [comment]
Good catch, works fine for me too.

**Pull request merged**
